// Code generated by go-bindata.
// sources:
// ../raw/create.sql
// DO NOT EDIT!

package files

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _RawCreateSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x74\x8f\x31\x6f\xc2\x30\x14\x84\x77\x7e\xc5\xdb\xb0\xa5\x0e\x45\xea\x50\xa9\x62\x30\xf0\x68\xad\x06\xd3\x26\xb6\x54\x26\x9c\x36\x2e\xf5\x50\x07\xc5\x4e\xc5\xcf\x2f\x7e\x48\x66\x62\xca\xe5\xbe\x3b\xeb\xde\xb2\x46\xa1\x11\xb4\x58\x54\x08\x72\x0d\x6a\xab\x01\x3f\x64\xa3\x1b\xb0\x87\xfe\xb3\xef\x53\xdc\x47\x17\xa3\xef\x2c\xb0\x09\x80\xcd\xc2\x87\xc4\x66\x33\x0e\x63\x88\xfe\x10\x5c\x47\x2d\x65\xaa\x0a\x84\xd1\xdb\xbd\x54\xe7\x57\x37\xa8\xf4\x5d\x2e\x50\xf5\xaf\x1d\xbe\x7e\xda\x81\x3d\xdc\xf3\x6b\x78\x85\x6b\x61\x2a\x0d\xd3\x29\x05\x93\xff\x75\x16\xba\x36\xb9\xac\x4a\x8c\xd8\x78\xcc\x7e\x77\x0b\xbb\xd3\xd1\x0f\x2e\xde\xc2\x67\xb7\xb5\x90\xdc\x29\xe5\xdf\xb7\x5a\x6e\x44\xbd\x83\x57\xdc\x01\xcb\xf7\xf0\xec\x1a\x25\xdf\x0d\x92\x79\x99\xcc\xe8\x43\x8c\xcc\x32\x81\x15\x79\x85\x65\x00\x2b\x92\x4f\x38\xa0\x7a\x96\x0a\xe7\x32\x84\x7e\xb5\x28\xf7\x2e\x5f\x44\xdd\xa0\x9e\x8f\xe9\xfb\xf1\xe9\x3f\x00\x00\xff\xff\x2e\xd6\xc8\x93\x81\x01\x00\x00")

func RawCreateSqlBytes() ([]byte, error) {
	return bindataRead(
		_RawCreateSql,
		"../raw/create.sql",
	)
}

func RawCreateSql() (*asset, error) {
	bytes, err := RawCreateSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "../raw/create.sql", size: 385, mode: os.FileMode(420), modTime: time.Unix(1476727508, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"../raw/create.sql": RawCreateSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"..": &bintree{nil, map[string]*bintree{
		"raw": &bintree{nil, map[string]*bintree{
			"create.sql": &bintree{RawCreateSql, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
